=== scorpion790/MaquinasVirtuales/Acceso Datos/XML,XPath,Xquery,Oracle/Ejercicios/Ejercicios resueltos/Ej1 DTD/datospersonales.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT persona ((nombre, apellido, DNI, fechanacimiento, direccion, telefono+, email+))>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT fechanacimiento ((dia, mes, anio))>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion ((calle, numero, poblacion, pais))>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>

=== scorpion790/MaquinasVirtuales/Acceso Datos/XML,XPath,Xquery,Oracle/Ejercicios/Enunciados/1DTD/datospersonales.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE persona SYSTEM "E:\Apuntes\Marcas\Lenguajes de Marcas 1DAM\UD5 Definición de esquemas y vocabularios XML\Ejercicios\Solhoja1XML\XML\datospersonales.dtd">
<persona>
	<nombre>Pepe</nombre>
	<apellido>Pinillos</apellido>
	<DNI>434235</DNI>
	<fechanacimiento>
		<dia>30</dia>
		<mes>3</mes>
		<anio>1976</anio>
	</fechanacimiento>
	<direccion>
		<calle>Avenida de la Felicidad</calle>
		<numero>34</numero>
		<poblacion>Villaarriba del Condado</poblacion>
		<pais>Libertonia</pais>
	</direccion>
	<telefono>987654321</telefono>
	<telefono>65431987</telefono>
	<email>ppinillos@hotmail.com</email>
	<email>pepito@hola.com</email>
</persona>
