=== scorpion790/MaquinasVirtuales/Acceso Datos/XML,XPath,Xquery,Oracle/Ejercicios/Ejercicios resueltos/Ej1 DTD/universidad.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT universidad (alumnos, profesores, asignaturas)>
<!ENTITY % datospersonales "nombre, apellido, apellido?, (DNI | (pasaporte, pais)), fechanacimiento, direccion?, telefono*, email*">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT pasaporte (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT fechanacimiento (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT alumnos (alumno)*>
<!ELEMENT alumno (%datospersonales;, matriculado*)>
<!ELEMENT matriculado EMPTY>
<!ATTLIST matriculado
	asignatura IDREF #REQUIRED
	nota (NP | AP | SS | NT | SB | MH) "NP"
>
<!ELEMENT profesores (profesor)*>
<!ELEMENT profesor (%datospersonales;, tutoria*)>
<!ATTLIST profesor
	despacho CDATA #REQUIRED
	asignaturas IDREFS #IMPLIED
>
<!ELEMENT tutoria (inicio, fin)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT fin (#PCDATA)>
<!ELEMENT asignaturas (asignatura)*>
<!ELEMENT asignatura (titulo, carrera, creditos, curso)>
<!ATTLIST asignatura
	codigo ID #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

=== scorpion790/MaquinasVirtuales/Acceso Datos/XML,XPath,Xquery,Oracle/Ejercicios/Enunciados/1DTD/universidad.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universidad SYSTEM "universidad.dtd">
<universidad>
	<alumnos>
		<alumno>
			<nombre>pepe</nombre>
			<apellido>pinillos</apellido>
			<pasaporte>434235</pasaporte>
			<pais>hola</pais>
			<fechanacimiento>
				<dia>32</dia>
				<mes>43</mes>
				<anio>5256</anio>
			</fechanacimiento>
			<matriculado asignatura="F89" nota="NT"/>
		</alumno>
	</alumnos>
	<profesores>
		<profesor despacho="" asignaturas="F89 A990">
			<nombre>Pepito</nombre>
			<apellido/>
			<DNI/>
			<fechanacimiento>
				<dia/>
				<mes/>
				<anio/>
			</fechanacimiento>
			<tutoria>
				<inicio/>
				<fin/>
			</tutoria>
		</profesor>
	</profesores>
	<asignaturas>
		<asignatura codigo="F89">
			<titulo>LMI</titulo>
			<carrera>ITIS</carrera>
			<creditos>4,5</creditos>
			<curso>OP</curso>
		</asignatura>
		<asignatura codigo="A990">
			<titulo>hola</titulo>
			<carrera/>
			<creditos/>
			<curso/>
		</asignatura>
	</asignaturas>
</universidad>
